export const PRIMARY_SKILL_OPTIONS = [
  "Frontend Development",
  "Backend Development",
  "Full Stack Development",
  "Mobile Development",
  "DevOps",
  "Cloud Computing",
  "Machine Learning",
  "Artificial Intelligence",
  "Data Science",
  "Data Analysis",
  "Cybersecurity",
  "UI/UX Design",
  "Product Management",
  "QA Testing",
  "Software Architecture",
  "Database Engineering",
  "Systems Programming",
  "Game Development",
  "Blockchain Development",
  "Embedded Systems",
] as const

export const TECHNOLOGY_OPTIONS = [
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Java",
  "Spring Boot",
  "Python",
  "Django",
  "Flask",
  "C",
  "C++",
  "C#",
  ".NET",
  "Go",
  "Rust",
  "PHP",
  "Laravel",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud",
  "Git",
  "GitHub",
  "Linux",
  "TensorFlow",
  "PyTorch",
  "OpenCV",
  "Figma",
  "Jenkins",
  "Terraform",
  "FastAPI",
  "GraphQL",
  "Tailwind CSS",
] as const

export function getProfileFocusAreas(primarySkills: string[] = [], technologies: string[] = []) {
  return Array.from(new Set([...(primarySkills || []), ...(technologies || [])].filter(Boolean))).sort((a, b) =>
    a.localeCompare(b)
  )
}
